# Generated by Django 3.2.9 on 2021-12-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipoServicio', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
